// =======================================================================
// token.rs
// =======================================================================
//! A wrapper around [`forj_parser::Token`]

use crate::Span;
use forj_parser::{self, PreprocessorCache};
use pyo3::prelude::*;

/// A wrapper around [`forj_parser::Token`]
#[pyclass(eq, from_py_object, module = "forj_python", str)]
#[derive(Clone, PartialEq, Eq)]
pub enum Token {
    Error(),
    // 1364-1995
    Always(),
    And(),
    Assign(),
    Begin(),
    Buf(),
    Bufif0(),
    Bufif1(),
    Case(),
    Casex(),
    Casez(),
    Cmos(),
    Deassign(),
    Default(),
    Defparam(),
    Disable(),
    Edge(),
    Else(),
    End(),
    Endcase(),
    Endfunction(),
    Endmodule(),
    Endprimitive(),
    Endspecify(),
    Endtable(),
    Endtask(),
    Event(),
    For(),
    Force(),
    Forever(),
    Fork(),
    Function(),
    Highz0(),
    Highz1(),
    If(),
    Ifnone(),
    Initial(),
    Inout(),
    Input(),
    Integer(),
    Join(),
    Large(),
    Macromodule(),
    Medium(),
    Module(),
    Nand(),
    Negedge(),
    Nmos(),
    Nor(),
    Not(),
    Notif0(),
    Notif1(),
    Or(),
    Output(),
    Parameter(),
    Pmos(),
    Posedge(),
    Primitive(),
    Pull0(),
    Pull1(),
    Pulldown(),
    Pullup(),
    Rcmos(),
    Real(),
    Realtime(),
    Reg(),
    Release(),
    Repeat(),
    Rnmos(),
    Rpmos(),
    Rtran(),
    Rtranif0(),
    Rtranif1(),
    Scalared(),
    Small(),
    Specify(),
    Specparam(),
    Strong0(),
    Strong1(),
    Supply0(),
    Supply1(),
    Table(),
    Task(),
    Time(),
    Tran(),
    Tranif0(),
    Tranif1(),
    Tri(),
    Tri0(),
    Tri1(),
    Triand(),
    Trior(),
    Trireg(),
    Vectored(),
    Wait(),
    Wand(),
    Weak0(),
    Weak1(),
    While(),
    Wire(),
    Wor(),
    Xnor(),
    Xor(),
    // 1364-2001
    Automatic(),
    Cell(),
    Config(),
    Design(),
    Endconfig(),
    Endgenerate(),
    Generate(),
    Genvar(),
    Incdir(),
    Include(),
    Instance(),
    Liblist(),
    Library(),
    Localparam(),
    Noshowcancelled(),
    PulsestyleOndetect(),
    PulsestyleOnevent(),
    Showcancelled(),
    Signed(),
    Unsigned(),
    Use(),
    // 1364-2005
    Uwire(),
    // 1800-2005
    Alias(),
    AlwaysComb(),
    AlwaysFf(),
    AlwaysLatch(),
    Assert(),
    Assume(),
    Before(),
    Bind(),
    Bins(),
    Binsof(),
    Bit(),
    Break(),
    Byte(),
    Chandle(),
    Class(),
    Clocking(),
    Const(),
    Constraint(),
    Context(),
    Continue(),
    Cover(),
    Covergroup(),
    Coverpoint(),
    Cross(),
    Dist(),
    Do(),
    Endclass(),
    Endclocking(),
    Endgroup(),
    Endinterface(),
    Endpackage(),
    Endprogram(),
    Endproperty(),
    Endsequence(),
    Enum(),
    Expect(),
    Export(),
    Extends(),
    Extern(),
    Final(),
    FirstMatch(),
    Foreach(),
    Forkjoin(),
    Iff(),
    IgnoreBins(),
    IllegalBins(),
    Import(),
    Inside(),
    Int(),
    Interface(),
    Intersect(),
    JoinAny(),
    JoinNone(),
    Local(),
    Logic(),
    Longint(),
    Matches(),
    Modport(),
    New(),
    Null(),
    Package(),
    Packed(),
    Priority(),
    Program(),
    Property(),
    Protected(),
    Pure(),
    Rand(),
    Randc(),
    Randcase(),
    Randsequence(),
    Ref(),
    Return(),
    Sequence(),
    Shortint(),
    Shortreal(),
    Solve(),
    Static(),
    String(),
    Struct(),
    Super(),
    Tagged(),
    This(),
    Throughout(),
    Timeprecision(),
    Timeunit(),
    Type(),
    Typedef(),
    Union(),
    Unique(),
    Var(),
    Virtual(),
    Void(),
    WaitOrder(),
    Wildcard(),
    With(),
    Within(),
    // 1800-2009
    AcceptOn(),
    Checker(),
    Endchecker(),
    Eventually(),
    Global(),
    Implies(),
    Let(),
    Nexttime(),
    RejectOn(),
    Restrict(),
    SAlways(),
    SEventually(),
    SNexttime(),
    SUntil(),
    SUntilWith(),
    Strong(),
    SyncAcceptOn(),
    SyncRejectOn(),
    Unique0(),
    Until(),
    UntilWith(),
    Untyped(),
    Weak(),
    // 1800-2012
    Implements(),
    Interconnect(),
    Nettype(),
    Soft(),
    // Directives
    DirUnderscoreFile(),
    DirUnderscoreLine(),
    DirBeginKeywords(),
    DirCelldefine(),
    DirDefaultNettype(),
    DirDefine(),
    DirElse(),
    DirElsif(),
    DirEndKeywords(),
    DirEndcelldefine(),
    DirEndif(),
    DirIfdef(),
    DirIfndef(),
    DirInclude(),
    DirLine(),
    DirNounconnectedDrive(),
    DirPragma(),
    DirResetall(),
    DirTimescale(),
    DirUnconnectedDrive(),
    DirUndef(),
    DirUndefineall(),
    // Operators
    Plus(),
    Minus(),
    Exclamation(),
    Quest(),
    Tilde(),
    Amp(),
    TildeAmp(),
    Pipe(),
    TildePipe(),
    Caret(),
    TildeCaret(),
    CaretTilde(),
    Star(),
    Slash(),
    Percent(),
    EqEq(),
    ExclEq(),
    PlusEq(),
    MinusEq(),
    StarEq(),
    SlashEq(),
    PercentEq(),
    AmpEq(),
    PipeEq(),
    CaretEq(),
    EqEqEq(),
    ExclEqEq(),
    EqEqQuest(),
    ExclEqQuest(),
    AmpAmp(),
    AmpAmpAmp(),
    PipePipe(),
    StarStar(),
    Lt(),
    LtEq(),
    Gt(),
    GtEq(),
    GtGt(),
    LtLt(),
    GtGtEq(),
    LtLtEq(),
    GtGtGt(),
    LtLtLt(),
    GtGtGtEq(),
    LtLtLtEq(),
    MinusGt(),
    MinusGtGt(),
    LtMinusGt(),
    PlusPlus(),
    MinusMinus(),
    PlusColon(),
    MinusColon(),
    PlusSlashMinus(),
    PlusPercentMinus(),
    // Symbols
    Paren(),
    EParen(),
    Bracket(),
    EBracket(),
    Brace(),
    EBrace(),
    Colon(),
    SColon(),
    Apost(),
    Comma(),
    Period(),
    Pound(),
    Dollar(),
    At(),
    AtAt(),
    Eq(),
    ColonColon(),
    ColonEq(),
    ColonSlash(),
    PoundPound(),
    PoundMinusPound(),
    PoundEqPound(),
    EqGt(),
    StarGt(),
    PipeMinusGt(),
    PipeEqGt(),
    Bslash(),
    // Other Language Grammar
    PathpulseDollar(),
    OneStep(),
    DollarSetup(),
    DollarHold(),
    DollarSetuphold(),
    DollarRecovery(),
    DollarRemoval(),
    DollarRecrem(),
    DollarSkew(),
    DollarTimeskew(),
    DollarFullskew(),
    DollarPeriod(),
    DollarWidth(),
    DollarNochange(),
    DollarRoot(),
    DollarUnit(),
    DollarFatal(),
    DollarError(),
    DollarWarning(),
    DollarInfo(),
    // Comments
    OnelineComment { text: String },
    BlockComment { text: String },
    // Numbers
    UnsignedNumber { text: String },
    FixedPointNumber { text: String },
    BinaryNumber { text: String },
    OctalNumber { text: String },
    DecimalNumber { text: String },
    HexNumber { text: String },
    ScientificNumber { text: String },
    UnbasedUnsizedLiteral { text: String },
    // Literals
    SystemTfIdentifier { text: String },
    SimpleIdentifier { text: String },
    EscapedIdentifier { text: String },
    PreprocessorIdentifier { text: String },
    TextMacro { text: String },
    ConcatenatedTextMacro { text: String },
    StringLiteral { text: String },
    PreprocessorStringLiteral { text: String },
    TripleQuoteStringLiteral { text: String },
    PreprocessorTripleQuoteStringLiteral { text: String },
    Newline(),
}

impl std::fmt::Display for Token {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let rust_token: forj_parser::Token<'_> = self.into();
        rust_token.fmt(f)
    }
}

impl<'a> From<forj_parser::Token<'a>> for Token {
    fn from(value: forj_parser::Token<'a>) -> Self {
        match value {
            forj_parser::Token::Error => Token::Error(),
            forj_parser::Token::Always => Token::Always(),
            forj_parser::Token::And => Token::And(),
            forj_parser::Token::Assign => Token::Assign(),
            forj_parser::Token::Begin => Token::Begin(),
            forj_parser::Token::Buf => Token::Buf(),
            forj_parser::Token::Bufif0 => Token::Bufif0(),
            forj_parser::Token::Bufif1 => Token::Bufif1(),
            forj_parser::Token::Case => Token::Case(),
            forj_parser::Token::Casex => Token::Casex(),
            forj_parser::Token::Casez => Token::Casez(),
            forj_parser::Token::Cmos => Token::Cmos(),
            forj_parser::Token::Deassign => Token::Deassign(),
            forj_parser::Token::Default => Token::Default(),
            forj_parser::Token::Defparam => Token::Defparam(),
            forj_parser::Token::Disable => Token::Disable(),
            forj_parser::Token::Edge => Token::Edge(),
            forj_parser::Token::Else => Token::Else(),
            forj_parser::Token::End => Token::End(),
            forj_parser::Token::Endcase => Token::Endcase(),
            forj_parser::Token::Endfunction => Token::Endfunction(),
            forj_parser::Token::Endmodule => Token::Endmodule(),
            forj_parser::Token::Endprimitive => Token::Endprimitive(),
            forj_parser::Token::Endspecify => Token::Endspecify(),
            forj_parser::Token::Endtable => Token::Endtable(),
            forj_parser::Token::Endtask => Token::Endtask(),
            forj_parser::Token::Event => Token::Event(),
            forj_parser::Token::For => Token::For(),
            forj_parser::Token::Force => Token::Force(),
            forj_parser::Token::Forever => Token::Forever(),
            forj_parser::Token::Fork => Token::Fork(),
            forj_parser::Token::Function => Token::Function(),
            forj_parser::Token::Highz0 => Token::Highz0(),
            forj_parser::Token::Highz1 => Token::Highz1(),
            forj_parser::Token::If => Token::If(),
            forj_parser::Token::Ifnone => Token::Ifnone(),
            forj_parser::Token::Initial => Token::Initial(),
            forj_parser::Token::Inout => Token::Inout(),
            forj_parser::Token::Input => Token::Input(),
            forj_parser::Token::Integer => Token::Integer(),
            forj_parser::Token::Join => Token::Join(),
            forj_parser::Token::Large => Token::Large(),
            forj_parser::Token::Macromodule => Token::Macromodule(),
            forj_parser::Token::Medium => Token::Medium(),
            forj_parser::Token::Module => Token::Module(),
            forj_parser::Token::Nand => Token::Nand(),
            forj_parser::Token::Negedge => Token::Negedge(),
            forj_parser::Token::Nmos => Token::Nmos(),
            forj_parser::Token::Nor => Token::Nor(),
            forj_parser::Token::Not => Token::Not(),
            forj_parser::Token::Notif0 => Token::Notif0(),
            forj_parser::Token::Notif1 => Token::Notif1(),
            forj_parser::Token::Or => Token::Or(),
            forj_parser::Token::Output => Token::Output(),
            forj_parser::Token::Parameter => Token::Parameter(),
            forj_parser::Token::Pmos => Token::Pmos(),
            forj_parser::Token::Posedge => Token::Posedge(),
            forj_parser::Token::Primitive => Token::Primitive(),
            forj_parser::Token::Pull0 => Token::Pull0(),
            forj_parser::Token::Pull1 => Token::Pull1(),
            forj_parser::Token::Pulldown => Token::Pulldown(),
            forj_parser::Token::Pullup => Token::Pullup(),
            forj_parser::Token::Rcmos => Token::Rcmos(),
            forj_parser::Token::Real => Token::Real(),
            forj_parser::Token::Realtime => Token::Realtime(),
            forj_parser::Token::Reg => Token::Reg(),
            forj_parser::Token::Release => Token::Release(),
            forj_parser::Token::Repeat => Token::Repeat(),
            forj_parser::Token::Rnmos => Token::Rnmos(),
            forj_parser::Token::Rpmos => Token::Rpmos(),
            forj_parser::Token::Rtran => Token::Rtran(),
            forj_parser::Token::Rtranif0 => Token::Rtranif0(),
            forj_parser::Token::Rtranif1 => Token::Rtranif1(),
            forj_parser::Token::Scalared => Token::Scalared(),
            forj_parser::Token::Small => Token::Small(),
            forj_parser::Token::Specify => Token::Specify(),
            forj_parser::Token::Specparam => Token::Specparam(),
            forj_parser::Token::Strong0 => Token::Strong0(),
            forj_parser::Token::Strong1 => Token::Strong1(),
            forj_parser::Token::Supply0 => Token::Supply0(),
            forj_parser::Token::Supply1 => Token::Supply1(),
            forj_parser::Token::Table => Token::Table(),
            forj_parser::Token::Task => Token::Task(),
            forj_parser::Token::Time => Token::Time(),
            forj_parser::Token::Tran => Token::Tran(),
            forj_parser::Token::Tranif0 => Token::Tranif0(),
            forj_parser::Token::Tranif1 => Token::Tranif1(),
            forj_parser::Token::Tri => Token::Tri(),
            forj_parser::Token::Tri0 => Token::Tri0(),
            forj_parser::Token::Tri1 => Token::Tri1(),
            forj_parser::Token::Triand => Token::Triand(),
            forj_parser::Token::Trior => Token::Trior(),
            forj_parser::Token::Trireg => Token::Trireg(),
            forj_parser::Token::Vectored => Token::Vectored(),
            forj_parser::Token::Wait => Token::Wait(),
            forj_parser::Token::Wand => Token::Wand(),
            forj_parser::Token::Weak0 => Token::Weak0(),
            forj_parser::Token::Weak1 => Token::Weak1(),
            forj_parser::Token::While => Token::While(),
            forj_parser::Token::Wire => Token::Wire(),
            forj_parser::Token::Wor => Token::Wor(),
            forj_parser::Token::Xnor => Token::Xnor(),
            forj_parser::Token::Xor => Token::Xor(),
            forj_parser::Token::Automatic => Token::Automatic(),
            forj_parser::Token::Cell => Token::Cell(),
            forj_parser::Token::Config => Token::Config(),
            forj_parser::Token::Design => Token::Design(),
            forj_parser::Token::Endconfig => Token::Endconfig(),
            forj_parser::Token::Endgenerate => Token::Endgenerate(),
            forj_parser::Token::Generate => Token::Generate(),
            forj_parser::Token::Genvar => Token::Genvar(),
            forj_parser::Token::Incdir => Token::Incdir(),
            forj_parser::Token::Include => Token::Include(),
            forj_parser::Token::Instance => Token::Instance(),
            forj_parser::Token::Liblist => Token::Liblist(),
            forj_parser::Token::Library => Token::Library(),
            forj_parser::Token::Localparam => Token::Localparam(),
            forj_parser::Token::Noshowcancelled => Token::Noshowcancelled(),
            forj_parser::Token::PulsestyleOndetect => {
                Token::PulsestyleOndetect()
            }
            forj_parser::Token::PulsestyleOnevent => Token::PulsestyleOnevent(),
            forj_parser::Token::Showcancelled => Token::Showcancelled(),
            forj_parser::Token::Signed => Token::Signed(),
            forj_parser::Token::Unsigned => Token::Unsigned(),
            forj_parser::Token::Use => Token::Use(),
            forj_parser::Token::Uwire => Token::Uwire(),
            forj_parser::Token::Alias => Token::Alias(),
            forj_parser::Token::AlwaysComb => Token::AlwaysComb(),
            forj_parser::Token::AlwaysFf => Token::AlwaysFf(),
            forj_parser::Token::AlwaysLatch => Token::AlwaysLatch(),
            forj_parser::Token::Assert => Token::Assert(),
            forj_parser::Token::Assume => Token::Assume(),
            forj_parser::Token::Before => Token::Before(),
            forj_parser::Token::Bind => Token::Bind(),
            forj_parser::Token::Bins => Token::Bins(),
            forj_parser::Token::Binsof => Token::Binsof(),
            forj_parser::Token::Bit => Token::Bit(),
            forj_parser::Token::Break => Token::Break(),
            forj_parser::Token::Byte => Token::Byte(),
            forj_parser::Token::Chandle => Token::Chandle(),
            forj_parser::Token::Class => Token::Class(),
            forj_parser::Token::Clocking => Token::Clocking(),
            forj_parser::Token::Const => Token::Const(),
            forj_parser::Token::Constraint => Token::Constraint(),
            forj_parser::Token::Context => Token::Context(),
            forj_parser::Token::Continue => Token::Continue(),
            forj_parser::Token::Cover => Token::Cover(),
            forj_parser::Token::Covergroup => Token::Covergroup(),
            forj_parser::Token::Coverpoint => Token::Coverpoint(),
            forj_parser::Token::Cross => Token::Cross(),
            forj_parser::Token::Dist => Token::Dist(),
            forj_parser::Token::Do => Token::Do(),
            forj_parser::Token::Endclass => Token::Endclass(),
            forj_parser::Token::Endclocking => Token::Endclocking(),
            forj_parser::Token::Endgroup => Token::Endgroup(),
            forj_parser::Token::Endinterface => Token::Endinterface(),
            forj_parser::Token::Endpackage => Token::Endpackage(),
            forj_parser::Token::Endprogram => Token::Endprogram(),
            forj_parser::Token::Endproperty => Token::Endproperty(),
            forj_parser::Token::Endsequence => Token::Endsequence(),
            forj_parser::Token::Enum => Token::Enum(),
            forj_parser::Token::Expect => Token::Expect(),
            forj_parser::Token::Export => Token::Export(),
            forj_parser::Token::Extends => Token::Extends(),
            forj_parser::Token::Extern => Token::Extern(),
            forj_parser::Token::Final => Token::Final(),
            forj_parser::Token::FirstMatch => Token::FirstMatch(),
            forj_parser::Token::Foreach => Token::Foreach(),
            forj_parser::Token::Forkjoin => Token::Forkjoin(),
            forj_parser::Token::Iff => Token::Iff(),
            forj_parser::Token::IgnoreBins => Token::IgnoreBins(),
            forj_parser::Token::IllegalBins => Token::IllegalBins(),
            forj_parser::Token::Import => Token::Import(),
            forj_parser::Token::Inside => Token::Inside(),
            forj_parser::Token::Int => Token::Int(),
            forj_parser::Token::Interface => Token::Interface(),
            forj_parser::Token::Intersect => Token::Intersect(),
            forj_parser::Token::JoinAny => Token::JoinAny(),
            forj_parser::Token::JoinNone => Token::JoinNone(),
            forj_parser::Token::Local => Token::Local(),
            forj_parser::Token::Logic => Token::Logic(),
            forj_parser::Token::Longint => Token::Longint(),
            forj_parser::Token::Matches => Token::Matches(),
            forj_parser::Token::Modport => Token::Modport(),
            forj_parser::Token::New => Token::New(),
            forj_parser::Token::Null => Token::Null(),
            forj_parser::Token::Package => Token::Package(),
            forj_parser::Token::Packed => Token::Packed(),
            forj_parser::Token::Priority => Token::Priority(),
            forj_parser::Token::Program => Token::Program(),
            forj_parser::Token::Property => Token::Property(),
            forj_parser::Token::Protected => Token::Protected(),
            forj_parser::Token::Pure => Token::Pure(),
            forj_parser::Token::Rand => Token::Rand(),
            forj_parser::Token::Randc => Token::Randc(),
            forj_parser::Token::Randcase => Token::Randcase(),
            forj_parser::Token::Randsequence => Token::Randsequence(),
            forj_parser::Token::Ref => Token::Ref(),
            forj_parser::Token::Return => Token::Return(),
            forj_parser::Token::Sequence => Token::Sequence(),
            forj_parser::Token::Shortint => Token::Shortint(),
            forj_parser::Token::Shortreal => Token::Shortreal(),
            forj_parser::Token::Solve => Token::Solve(),
            forj_parser::Token::Static => Token::Static(),
            forj_parser::Token::String => Token::String(),
            forj_parser::Token::Struct => Token::Struct(),
            forj_parser::Token::Super => Token::Super(),
            forj_parser::Token::Tagged => Token::Tagged(),
            forj_parser::Token::This => Token::This(),
            forj_parser::Token::Throughout => Token::Throughout(),
            forj_parser::Token::Timeprecision => Token::Timeprecision(),
            forj_parser::Token::Timeunit => Token::Timeunit(),
            forj_parser::Token::Type => Token::Type(),
            forj_parser::Token::Typedef => Token::Typedef(),
            forj_parser::Token::Union => Token::Union(),
            forj_parser::Token::Unique => Token::Unique(),
            forj_parser::Token::Var => Token::Var(),
            forj_parser::Token::Virtual => Token::Virtual(),
            forj_parser::Token::Void => Token::Void(),
            forj_parser::Token::WaitOrder => Token::WaitOrder(),
            forj_parser::Token::Wildcard => Token::Wildcard(),
            forj_parser::Token::With => Token::With(),
            forj_parser::Token::Within => Token::Within(),
            forj_parser::Token::AcceptOn => Token::AcceptOn(),
            forj_parser::Token::Checker => Token::Checker(),
            forj_parser::Token::Endchecker => Token::Endchecker(),
            forj_parser::Token::Eventually => Token::Eventually(),
            forj_parser::Token::Global => Token::Global(),
            forj_parser::Token::Implies => Token::Implies(),
            forj_parser::Token::Let => Token::Let(),
            forj_parser::Token::Nexttime => Token::Nexttime(),
            forj_parser::Token::RejectOn => Token::RejectOn(),
            forj_parser::Token::Restrict => Token::Restrict(),
            forj_parser::Token::SAlways => Token::SAlways(),
            forj_parser::Token::SEventually => Token::SEventually(),
            forj_parser::Token::SNexttime => Token::SNexttime(),
            forj_parser::Token::SUntil => Token::SUntil(),
            forj_parser::Token::SUntilWith => Token::SUntilWith(),
            forj_parser::Token::Strong => Token::Strong(),
            forj_parser::Token::SyncAcceptOn => Token::SyncAcceptOn(),
            forj_parser::Token::SyncRejectOn => Token::SyncRejectOn(),
            forj_parser::Token::Unique0 => Token::Unique0(),
            forj_parser::Token::Until => Token::Until(),
            forj_parser::Token::UntilWith => Token::UntilWith(),
            forj_parser::Token::Untyped => Token::Untyped(),
            forj_parser::Token::Weak => Token::Weak(),
            forj_parser::Token::Implements => Token::Implements(),
            forj_parser::Token::Interconnect => Token::Interconnect(),
            forj_parser::Token::Nettype => Token::Nettype(),
            forj_parser::Token::Soft => Token::Soft(),
            forj_parser::Token::DirUnderscoreFile => Token::DirUnderscoreFile(),
            forj_parser::Token::DirUnderscoreLine => Token::DirUnderscoreLine(),
            forj_parser::Token::DirBeginKeywords => Token::DirBeginKeywords(),
            forj_parser::Token::DirCelldefine => Token::DirCelldefine(),
            forj_parser::Token::DirDefaultNettype => Token::DirDefaultNettype(),
            forj_parser::Token::DirDefine => Token::DirDefine(),
            forj_parser::Token::DirElse => Token::DirElse(),
            forj_parser::Token::DirElsif => Token::DirElsif(),
            forj_parser::Token::DirEndKeywords => Token::DirEndKeywords(),
            forj_parser::Token::DirEndcelldefine => Token::DirEndcelldefine(),
            forj_parser::Token::DirEndif => Token::DirEndif(),
            forj_parser::Token::DirIfdef => Token::DirIfdef(),
            forj_parser::Token::DirIfndef => Token::DirIfndef(),
            forj_parser::Token::DirInclude => Token::DirInclude(),
            forj_parser::Token::DirLine => Token::DirLine(),
            forj_parser::Token::DirNounconnectedDrive => {
                Token::DirNounconnectedDrive()
            }
            forj_parser::Token::DirPragma => Token::DirPragma(),
            forj_parser::Token::DirResetall => Token::DirResetall(),
            forj_parser::Token::DirTimescale => Token::DirTimescale(),
            forj_parser::Token::DirUnconnectedDrive => {
                Token::DirUnconnectedDrive()
            }
            forj_parser::Token::DirUndef => Token::DirUndef(),
            forj_parser::Token::DirUndefineall => Token::DirUndefineall(),
            forj_parser::Token::Plus => Token::Plus(),
            forj_parser::Token::Minus => Token::Minus(),
            forj_parser::Token::Exclamation => Token::Exclamation(),
            forj_parser::Token::Quest => Token::Quest(),
            forj_parser::Token::Tilde => Token::Tilde(),
            forj_parser::Token::Amp => Token::Amp(),
            forj_parser::Token::TildeAmp => Token::TildeAmp(),
            forj_parser::Token::Pipe => Token::Pipe(),
            forj_parser::Token::TildePipe => Token::TildePipe(),
            forj_parser::Token::Caret => Token::Caret(),
            forj_parser::Token::TildeCaret => Token::TildeCaret(),
            forj_parser::Token::CaretTilde => Token::CaretTilde(),
            forj_parser::Token::Star => Token::Star(),
            forj_parser::Token::Slash => Token::Slash(),
            forj_parser::Token::Percent => Token::Percent(),
            forj_parser::Token::EqEq => Token::EqEq(),
            forj_parser::Token::ExclEq => Token::ExclEq(),
            forj_parser::Token::PlusEq => Token::PlusEq(),
            forj_parser::Token::MinusEq => Token::MinusEq(),
            forj_parser::Token::StarEq => Token::StarEq(),
            forj_parser::Token::SlashEq => Token::SlashEq(),
            forj_parser::Token::PercentEq => Token::PercentEq(),
            forj_parser::Token::AmpEq => Token::AmpEq(),
            forj_parser::Token::PipeEq => Token::PipeEq(),
            forj_parser::Token::CaretEq => Token::CaretEq(),
            forj_parser::Token::EqEqEq => Token::EqEqEq(),
            forj_parser::Token::ExclEqEq => Token::ExclEqEq(),
            forj_parser::Token::EqEqQuest => Token::EqEqQuest(),
            forj_parser::Token::ExclEqQuest => Token::ExclEqQuest(),
            forj_parser::Token::AmpAmp => Token::AmpAmp(),
            forj_parser::Token::AmpAmpAmp => Token::AmpAmpAmp(),
            forj_parser::Token::PipePipe => Token::PipePipe(),
            forj_parser::Token::StarStar => Token::StarStar(),
            forj_parser::Token::Lt => Token::Lt(),
            forj_parser::Token::LtEq => Token::LtEq(),
            forj_parser::Token::Gt => Token::Gt(),
            forj_parser::Token::GtEq => Token::GtEq(),
            forj_parser::Token::GtGt => Token::GtGt(),
            forj_parser::Token::LtLt => Token::LtLt(),
            forj_parser::Token::GtGtEq => Token::GtGtEq(),
            forj_parser::Token::LtLtEq => Token::LtLtEq(),
            forj_parser::Token::GtGtGt => Token::GtGtGt(),
            forj_parser::Token::LtLtLt => Token::LtLtLt(),
            forj_parser::Token::GtGtGtEq => Token::GtGtGtEq(),
            forj_parser::Token::LtLtLtEq => Token::LtLtLtEq(),
            forj_parser::Token::MinusGt => Token::MinusGt(),
            forj_parser::Token::MinusGtGt => Token::MinusGtGt(),
            forj_parser::Token::LtMinusGt => Token::LtMinusGt(),
            forj_parser::Token::PlusPlus => Token::PlusPlus(),
            forj_parser::Token::MinusMinus => Token::MinusMinus(),
            forj_parser::Token::PlusColon => Token::PlusColon(),
            forj_parser::Token::MinusColon => Token::MinusColon(),
            forj_parser::Token::PlusSlashMinus => Token::PlusSlashMinus(),
            forj_parser::Token::PlusPercentMinus => Token::PlusPercentMinus(),
            forj_parser::Token::Paren => Token::Paren(),
            forj_parser::Token::EParen => Token::EParen(),
            forj_parser::Token::Bracket => Token::Bracket(),
            forj_parser::Token::EBracket => Token::EBracket(),
            forj_parser::Token::Brace => Token::Brace(),
            forj_parser::Token::EBrace => Token::EBrace(),
            forj_parser::Token::Colon => Token::Colon(),
            forj_parser::Token::SColon => Token::SColon(),
            forj_parser::Token::Apost => Token::Apost(),
            forj_parser::Token::Comma => Token::Comma(),
            forj_parser::Token::Period => Token::Period(),
            forj_parser::Token::Pound => Token::Pound(),
            forj_parser::Token::Dollar => Token::Dollar(),
            forj_parser::Token::At => Token::At(),
            forj_parser::Token::AtAt => Token::AtAt(),
            forj_parser::Token::Eq => Token::Eq(),
            forj_parser::Token::ColonColon => Token::ColonColon(),
            forj_parser::Token::ColonEq => Token::ColonEq(),
            forj_parser::Token::ColonSlash => Token::ColonSlash(),
            forj_parser::Token::PoundPound => Token::PoundPound(),
            forj_parser::Token::PoundMinusPound => Token::PoundMinusPound(),
            forj_parser::Token::PoundEqPound => Token::PoundEqPound(),
            forj_parser::Token::EqGt => Token::EqGt(),
            forj_parser::Token::StarGt => Token::StarGt(),
            forj_parser::Token::PipeMinusGt => Token::PipeMinusGt(),
            forj_parser::Token::PipeEqGt => Token::PipeEqGt(),
            forj_parser::Token::Bslash => Token::Bslash(),
            forj_parser::Token::PathpulseDollar => Token::PathpulseDollar(),
            forj_parser::Token::OneStep => Token::OneStep(),
            forj_parser::Token::DollarSetup => Token::DollarSetup(),
            forj_parser::Token::DollarHold => Token::DollarHold(),
            forj_parser::Token::DollarSetuphold => Token::DollarSetuphold(),
            forj_parser::Token::DollarRecovery => Token::DollarRecovery(),
            forj_parser::Token::DollarRemoval => Token::DollarRemoval(),
            forj_parser::Token::DollarRecrem => Token::DollarRecrem(),
            forj_parser::Token::DollarSkew => Token::DollarSkew(),
            forj_parser::Token::DollarTimeskew => Token::DollarTimeskew(),
            forj_parser::Token::DollarFullskew => Token::DollarFullskew(),
            forj_parser::Token::DollarPeriod => Token::DollarPeriod(),
            forj_parser::Token::DollarWidth => Token::DollarWidth(),
            forj_parser::Token::DollarNochange => Token::DollarNochange(),
            forj_parser::Token::DollarRoot => Token::DollarRoot(),
            forj_parser::Token::DollarUnit => Token::DollarUnit(),
            forj_parser::Token::DollarFatal => Token::DollarFatal(),
            forj_parser::Token::DollarError => Token::DollarError(),
            forj_parser::Token::DollarWarning => Token::DollarWarning(),
            forj_parser::Token::DollarInfo => Token::DollarInfo(),
            forj_parser::Token::OnelineComment(str) => Token::OnelineComment {
                text: str.to_string(),
            },
            forj_parser::Token::BlockComment(str) => Token::BlockComment {
                text: str.to_string(),
            },
            forj_parser::Token::UnsignedNumber(str) => Token::UnsignedNumber {
                text: str.to_string(),
            },
            forj_parser::Token::FixedPointNumber(str) => {
                Token::FixedPointNumber {
                    text: str.to_string(),
                }
            }
            forj_parser::Token::BinaryNumber(str) => Token::BinaryNumber {
                text: str.to_string(),
            },
            forj_parser::Token::OctalNumber(str) => Token::OctalNumber {
                text: str.to_string(),
            },
            forj_parser::Token::DecimalNumber(str) => Token::DecimalNumber {
                text: str.to_string(),
            },
            forj_parser::Token::HexNumber(str) => Token::HexNumber {
                text: str.to_string(),
            },
            forj_parser::Token::ScientificNumber(str) => {
                Token::ScientificNumber {
                    text: str.to_string(),
                }
            }
            forj_parser::Token::UnbasedUnsizedLiteral(str) => {
                Token::UnbasedUnsizedLiteral {
                    text: str.to_string(),
                }
            }
            forj_parser::Token::SystemTfIdentifier(str) => {
                Token::SystemTfIdentifier {
                    text: str.to_string(),
                }
            }
            forj_parser::Token::SimpleIdentifier(str) => {
                Token::SimpleIdentifier {
                    text: str.to_string(),
                }
            }
            forj_parser::Token::EscapedIdentifier(str) => {
                Token::EscapedIdentifier {
                    text: str.to_string(),
                }
            }
            forj_parser::Token::PreprocessorIdentifier(str) => {
                Token::PreprocessorIdentifier {
                    text: str.to_string(),
                }
            }
            forj_parser::Token::TextMacro(str) => Token::TextMacro {
                text: str.to_string(),
            },
            forj_parser::Token::ConcatenatedTextMacro(str) => {
                Token::ConcatenatedTextMacro {
                    text: str.to_string(),
                }
            }
            forj_parser::Token::StringLiteral(str) => Token::StringLiteral {
                text: str.to_string(),
            },
            forj_parser::Token::PreprocessorStringLiteral(str) => {
                Token::PreprocessorStringLiteral {
                    text: str.to_string(),
                }
            }
            forj_parser::Token::TripleQuoteStringLiteral(str) => {
                Token::TripleQuoteStringLiteral {
                    text: str.to_string(),
                }
            }
            forj_parser::Token::PreprocessorTripleQuoteStringLiteral(str) => {
                Token::PreprocessorTripleQuoteStringLiteral {
                    text: str.to_string(),
                }
            }
            forj_parser::Token::Newline => Token::Newline(),
        }
    }
}

impl<'a> From<&'a Token> for forj_parser::Token<'a> {
    fn from(value: &'a Token) -> Self {
        match value {
            Token::Error() => forj_parser::Token::Error,
            Token::Always() => forj_parser::Token::Always,
            Token::And() => forj_parser::Token::And,
            Token::Assign() => forj_parser::Token::Assign,
            Token::Begin() => forj_parser::Token::Begin,
            Token::Buf() => forj_parser::Token::Buf,
            Token::Bufif0() => forj_parser::Token::Bufif0,
            Token::Bufif1() => forj_parser::Token::Bufif1,
            Token::Case() => forj_parser::Token::Case,
            Token::Casex() => forj_parser::Token::Casex,
            Token::Casez() => forj_parser::Token::Casez,
            Token::Cmos() => forj_parser::Token::Cmos,
            Token::Deassign() => forj_parser::Token::Deassign,
            Token::Default() => forj_parser::Token::Default,
            Token::Defparam() => forj_parser::Token::Defparam,
            Token::Disable() => forj_parser::Token::Disable,
            Token::Edge() => forj_parser::Token::Edge,
            Token::Else() => forj_parser::Token::Else,
            Token::End() => forj_parser::Token::End,
            Token::Endcase() => forj_parser::Token::Endcase,
            Token::Endfunction() => forj_parser::Token::Endfunction,
            Token::Endmodule() => forj_parser::Token::Endmodule,
            Token::Endprimitive() => forj_parser::Token::Endprimitive,
            Token::Endspecify() => forj_parser::Token::Endspecify,
            Token::Endtable() => forj_parser::Token::Endtable,
            Token::Endtask() => forj_parser::Token::Endtask,
            Token::Event() => forj_parser::Token::Event,
            Token::For() => forj_parser::Token::For,
            Token::Force() => forj_parser::Token::Force,
            Token::Forever() => forj_parser::Token::Forever,
            Token::Fork() => forj_parser::Token::Fork,
            Token::Function() => forj_parser::Token::Function,
            Token::Highz0() => forj_parser::Token::Highz0,
            Token::Highz1() => forj_parser::Token::Highz1,
            Token::If() => forj_parser::Token::If,
            Token::Ifnone() => forj_parser::Token::Ifnone,
            Token::Initial() => forj_parser::Token::Initial,
            Token::Inout() => forj_parser::Token::Inout,
            Token::Input() => forj_parser::Token::Input,
            Token::Integer() => forj_parser::Token::Integer,
            Token::Join() => forj_parser::Token::Join,
            Token::Large() => forj_parser::Token::Large,
            Token::Macromodule() => forj_parser::Token::Macromodule,
            Token::Medium() => forj_parser::Token::Medium,
            Token::Module() => forj_parser::Token::Module,
            Token::Nand() => forj_parser::Token::Nand,
            Token::Negedge() => forj_parser::Token::Negedge,
            Token::Nmos() => forj_parser::Token::Nmos,
            Token::Nor() => forj_parser::Token::Nor,
            Token::Not() => forj_parser::Token::Not,
            Token::Notif0() => forj_parser::Token::Notif0,
            Token::Notif1() => forj_parser::Token::Notif1,
            Token::Or() => forj_parser::Token::Or,
            Token::Output() => forj_parser::Token::Output,
            Token::Parameter() => forj_parser::Token::Parameter,
            Token::Pmos() => forj_parser::Token::Pmos,
            Token::Posedge() => forj_parser::Token::Posedge,
            Token::Primitive() => forj_parser::Token::Primitive,
            Token::Pull0() => forj_parser::Token::Pull0,
            Token::Pull1() => forj_parser::Token::Pull1,
            Token::Pulldown() => forj_parser::Token::Pulldown,
            Token::Pullup() => forj_parser::Token::Pullup,
            Token::Rcmos() => forj_parser::Token::Rcmos,
            Token::Real() => forj_parser::Token::Real,
            Token::Realtime() => forj_parser::Token::Realtime,
            Token::Reg() => forj_parser::Token::Reg,
            Token::Release() => forj_parser::Token::Release,
            Token::Repeat() => forj_parser::Token::Repeat,
            Token::Rnmos() => forj_parser::Token::Rnmos,
            Token::Rpmos() => forj_parser::Token::Rpmos,
            Token::Rtran() => forj_parser::Token::Rtran,
            Token::Rtranif0() => forj_parser::Token::Rtranif0,
            Token::Rtranif1() => forj_parser::Token::Rtranif1,
            Token::Scalared() => forj_parser::Token::Scalared,
            Token::Small() => forj_parser::Token::Small,
            Token::Specify() => forj_parser::Token::Specify,
            Token::Specparam() => forj_parser::Token::Specparam,
            Token::Strong0() => forj_parser::Token::Strong0,
            Token::Strong1() => forj_parser::Token::Strong1,
            Token::Supply0() => forj_parser::Token::Supply0,
            Token::Supply1() => forj_parser::Token::Supply1,
            Token::Table() => forj_parser::Token::Table,
            Token::Task() => forj_parser::Token::Task,
            Token::Time() => forj_parser::Token::Time,
            Token::Tran() => forj_parser::Token::Tran,
            Token::Tranif0() => forj_parser::Token::Tranif0,
            Token::Tranif1() => forj_parser::Token::Tranif1,
            Token::Tri() => forj_parser::Token::Tri,
            Token::Tri0() => forj_parser::Token::Tri0,
            Token::Tri1() => forj_parser::Token::Tri1,
            Token::Triand() => forj_parser::Token::Triand,
            Token::Trior() => forj_parser::Token::Trior,
            Token::Trireg() => forj_parser::Token::Trireg,
            Token::Vectored() => forj_parser::Token::Vectored,
            Token::Wait() => forj_parser::Token::Wait,
            Token::Wand() => forj_parser::Token::Wand,
            Token::Weak0() => forj_parser::Token::Weak0,
            Token::Weak1() => forj_parser::Token::Weak1,
            Token::While() => forj_parser::Token::While,
            Token::Wire() => forj_parser::Token::Wire,
            Token::Wor() => forj_parser::Token::Wor,
            Token::Xnor() => forj_parser::Token::Xnor,
            Token::Xor() => forj_parser::Token::Xor,
            Token::Automatic() => forj_parser::Token::Automatic,
            Token::Cell() => forj_parser::Token::Cell,
            Token::Config() => forj_parser::Token::Config,
            Token::Design() => forj_parser::Token::Design,
            Token::Endconfig() => forj_parser::Token::Endconfig,
            Token::Endgenerate() => forj_parser::Token::Endgenerate,
            Token::Generate() => forj_parser::Token::Generate,
            Token::Genvar() => forj_parser::Token::Genvar,
            Token::Incdir() => forj_parser::Token::Incdir,
            Token::Include() => forj_parser::Token::Include,
            Token::Instance() => forj_parser::Token::Instance,
            Token::Liblist() => forj_parser::Token::Liblist,
            Token::Library() => forj_parser::Token::Library,
            Token::Localparam() => forj_parser::Token::Localparam,
            Token::Noshowcancelled() => forj_parser::Token::Noshowcancelled,
            Token::PulsestyleOndetect() => {
                forj_parser::Token::PulsestyleOndetect
            }
            Token::PulsestyleOnevent() => forj_parser::Token::PulsestyleOnevent,
            Token::Showcancelled() => forj_parser::Token::Showcancelled,
            Token::Signed() => forj_parser::Token::Signed,
            Token::Unsigned() => forj_parser::Token::Unsigned,
            Token::Use() => forj_parser::Token::Use,
            Token::Uwire() => forj_parser::Token::Uwire,
            Token::Alias() => forj_parser::Token::Alias,
            Token::AlwaysComb() => forj_parser::Token::AlwaysComb,
            Token::AlwaysFf() => forj_parser::Token::AlwaysFf,
            Token::AlwaysLatch() => forj_parser::Token::AlwaysLatch,
            Token::Assert() => forj_parser::Token::Assert,
            Token::Assume() => forj_parser::Token::Assume,
            Token::Before() => forj_parser::Token::Before,
            Token::Bind() => forj_parser::Token::Bind,
            Token::Bins() => forj_parser::Token::Bins,
            Token::Binsof() => forj_parser::Token::Binsof,
            Token::Bit() => forj_parser::Token::Bit,
            Token::Break() => forj_parser::Token::Break,
            Token::Byte() => forj_parser::Token::Byte,
            Token::Chandle() => forj_parser::Token::Chandle,
            Token::Class() => forj_parser::Token::Class,
            Token::Clocking() => forj_parser::Token::Clocking,
            Token::Const() => forj_parser::Token::Const,
            Token::Constraint() => forj_parser::Token::Constraint,
            Token::Context() => forj_parser::Token::Context,
            Token::Continue() => forj_parser::Token::Continue,
            Token::Cover() => forj_parser::Token::Cover,
            Token::Covergroup() => forj_parser::Token::Covergroup,
            Token::Coverpoint() => forj_parser::Token::Coverpoint,
            Token::Cross() => forj_parser::Token::Cross,
            Token::Dist() => forj_parser::Token::Dist,
            Token::Do() => forj_parser::Token::Do,
            Token::Endclass() => forj_parser::Token::Endclass,
            Token::Endclocking() => forj_parser::Token::Endclocking,
            Token::Endgroup() => forj_parser::Token::Endgroup,
            Token::Endinterface() => forj_parser::Token::Endinterface,
            Token::Endpackage() => forj_parser::Token::Endpackage,
            Token::Endprogram() => forj_parser::Token::Endprogram,
            Token::Endproperty() => forj_parser::Token::Endproperty,
            Token::Endsequence() => forj_parser::Token::Endsequence,
            Token::Enum() => forj_parser::Token::Enum,
            Token::Expect() => forj_parser::Token::Expect,
            Token::Export() => forj_parser::Token::Export,
            Token::Extends() => forj_parser::Token::Extends,
            Token::Extern() => forj_parser::Token::Extern,
            Token::Final() => forj_parser::Token::Final,
            Token::FirstMatch() => forj_parser::Token::FirstMatch,
            Token::Foreach() => forj_parser::Token::Foreach,
            Token::Forkjoin() => forj_parser::Token::Forkjoin,
            Token::Iff() => forj_parser::Token::Iff,
            Token::IgnoreBins() => forj_parser::Token::IgnoreBins,
            Token::IllegalBins() => forj_parser::Token::IllegalBins,
            Token::Import() => forj_parser::Token::Import,
            Token::Inside() => forj_parser::Token::Inside,
            Token::Int() => forj_parser::Token::Int,
            Token::Interface() => forj_parser::Token::Interface,
            Token::Intersect() => forj_parser::Token::Intersect,
            Token::JoinAny() => forj_parser::Token::JoinAny,
            Token::JoinNone() => forj_parser::Token::JoinNone,
            Token::Local() => forj_parser::Token::Local,
            Token::Logic() => forj_parser::Token::Logic,
            Token::Longint() => forj_parser::Token::Longint,
            Token::Matches() => forj_parser::Token::Matches,
            Token::Modport() => forj_parser::Token::Modport,
            Token::New() => forj_parser::Token::New,
            Token::Null() => forj_parser::Token::Null,
            Token::Package() => forj_parser::Token::Package,
            Token::Packed() => forj_parser::Token::Packed,
            Token::Priority() => forj_parser::Token::Priority,
            Token::Program() => forj_parser::Token::Program,
            Token::Property() => forj_parser::Token::Property,
            Token::Protected() => forj_parser::Token::Protected,
            Token::Pure() => forj_parser::Token::Pure,
            Token::Rand() => forj_parser::Token::Rand,
            Token::Randc() => forj_parser::Token::Randc,
            Token::Randcase() => forj_parser::Token::Randcase,
            Token::Randsequence() => forj_parser::Token::Randsequence,
            Token::Ref() => forj_parser::Token::Ref,
            Token::Return() => forj_parser::Token::Return,
            Token::Sequence() => forj_parser::Token::Sequence,
            Token::Shortint() => forj_parser::Token::Shortint,
            Token::Shortreal() => forj_parser::Token::Shortreal,
            Token::Solve() => forj_parser::Token::Solve,
            Token::Static() => forj_parser::Token::Static,
            Token::String() => forj_parser::Token::String,
            Token::Struct() => forj_parser::Token::Struct,
            Token::Super() => forj_parser::Token::Super,
            Token::Tagged() => forj_parser::Token::Tagged,
            Token::This() => forj_parser::Token::This,
            Token::Throughout() => forj_parser::Token::Throughout,
            Token::Timeprecision() => forj_parser::Token::Timeprecision,
            Token::Timeunit() => forj_parser::Token::Timeunit,
            Token::Type() => forj_parser::Token::Type,
            Token::Typedef() => forj_parser::Token::Typedef,
            Token::Union() => forj_parser::Token::Union,
            Token::Unique() => forj_parser::Token::Unique,
            Token::Var() => forj_parser::Token::Var,
            Token::Virtual() => forj_parser::Token::Virtual,
            Token::Void() => forj_parser::Token::Void,
            Token::WaitOrder() => forj_parser::Token::WaitOrder,
            Token::Wildcard() => forj_parser::Token::Wildcard,
            Token::With() => forj_parser::Token::With,
            Token::Within() => forj_parser::Token::Within,
            Token::AcceptOn() => forj_parser::Token::AcceptOn,
            Token::Checker() => forj_parser::Token::Checker,
            Token::Endchecker() => forj_parser::Token::Endchecker,
            Token::Eventually() => forj_parser::Token::Eventually,
            Token::Global() => forj_parser::Token::Global,
            Token::Implies() => forj_parser::Token::Implies,
            Token::Let() => forj_parser::Token::Let,
            Token::Nexttime() => forj_parser::Token::Nexttime,
            Token::RejectOn() => forj_parser::Token::RejectOn,
            Token::Restrict() => forj_parser::Token::Restrict,
            Token::SAlways() => forj_parser::Token::SAlways,
            Token::SEventually() => forj_parser::Token::SEventually,
            Token::SNexttime() => forj_parser::Token::SNexttime,
            Token::SUntil() => forj_parser::Token::SUntil,
            Token::SUntilWith() => forj_parser::Token::SUntilWith,
            Token::Strong() => forj_parser::Token::Strong,
            Token::SyncAcceptOn() => forj_parser::Token::SyncAcceptOn,
            Token::SyncRejectOn() => forj_parser::Token::SyncRejectOn,
            Token::Unique0() => forj_parser::Token::Unique0,
            Token::Until() => forj_parser::Token::Until,
            Token::UntilWith() => forj_parser::Token::UntilWith,
            Token::Untyped() => forj_parser::Token::Untyped,
            Token::Weak() => forj_parser::Token::Weak,
            Token::Implements() => forj_parser::Token::Implements,
            Token::Interconnect() => forj_parser::Token::Interconnect,
            Token::Nettype() => forj_parser::Token::Nettype,
            Token::Soft() => forj_parser::Token::Soft,
            Token::DirUnderscoreFile() => forj_parser::Token::DirUnderscoreFile,
            Token::DirUnderscoreLine() => forj_parser::Token::DirUnderscoreLine,
            Token::DirBeginKeywords() => forj_parser::Token::DirBeginKeywords,
            Token::DirCelldefine() => forj_parser::Token::DirCelldefine,
            Token::DirDefaultNettype() => forj_parser::Token::DirDefaultNettype,
            Token::DirDefine() => forj_parser::Token::DirDefine,
            Token::DirElse() => forj_parser::Token::DirElse,
            Token::DirElsif() => forj_parser::Token::DirElsif,
            Token::DirEndKeywords() => forj_parser::Token::DirEndKeywords,
            Token::DirEndcelldefine() => forj_parser::Token::DirEndcelldefine,
            Token::DirEndif() => forj_parser::Token::DirEndif,
            Token::DirIfdef() => forj_parser::Token::DirIfdef,
            Token::DirIfndef() => forj_parser::Token::DirIfndef,
            Token::DirInclude() => forj_parser::Token::DirInclude,
            Token::DirLine() => forj_parser::Token::DirLine,
            Token::DirNounconnectedDrive() => {
                forj_parser::Token::DirNounconnectedDrive
            }
            Token::DirPragma() => forj_parser::Token::DirPragma,
            Token::DirResetall() => forj_parser::Token::DirResetall,
            Token::DirTimescale() => forj_parser::Token::DirTimescale,
            Token::DirUnconnectedDrive() => {
                forj_parser::Token::DirUnconnectedDrive
            }
            Token::DirUndef() => forj_parser::Token::DirUndef,
            Token::DirUndefineall() => forj_parser::Token::DirUndefineall,
            Token::Plus() => forj_parser::Token::Plus,
            Token::Minus() => forj_parser::Token::Minus,
            Token::Exclamation() => forj_parser::Token::Exclamation,
            Token::Quest() => forj_parser::Token::Quest,
            Token::Tilde() => forj_parser::Token::Tilde,
            Token::Amp() => forj_parser::Token::Amp,
            Token::TildeAmp() => forj_parser::Token::TildeAmp,
            Token::Pipe() => forj_parser::Token::Pipe,
            Token::TildePipe() => forj_parser::Token::TildePipe,
            Token::Caret() => forj_parser::Token::Caret,
            Token::TildeCaret() => forj_parser::Token::TildeCaret,
            Token::CaretTilde() => forj_parser::Token::CaretTilde,
            Token::Star() => forj_parser::Token::Star,
            Token::Slash() => forj_parser::Token::Slash,
            Token::Percent() => forj_parser::Token::Percent,
            Token::EqEq() => forj_parser::Token::EqEq,
            Token::ExclEq() => forj_parser::Token::ExclEq,
            Token::PlusEq() => forj_parser::Token::PlusEq,
            Token::MinusEq() => forj_parser::Token::MinusEq,
            Token::StarEq() => forj_parser::Token::StarEq,
            Token::SlashEq() => forj_parser::Token::SlashEq,
            Token::PercentEq() => forj_parser::Token::PercentEq,
            Token::AmpEq() => forj_parser::Token::AmpEq,
            Token::PipeEq() => forj_parser::Token::PipeEq,
            Token::CaretEq() => forj_parser::Token::CaretEq,
            Token::EqEqEq() => forj_parser::Token::EqEqEq,
            Token::ExclEqEq() => forj_parser::Token::ExclEqEq,
            Token::EqEqQuest() => forj_parser::Token::EqEqQuest,
            Token::ExclEqQuest() => forj_parser::Token::ExclEqQuest,
            Token::AmpAmp() => forj_parser::Token::AmpAmp,
            Token::AmpAmpAmp() => forj_parser::Token::AmpAmpAmp,
            Token::PipePipe() => forj_parser::Token::PipePipe,
            Token::StarStar() => forj_parser::Token::StarStar,
            Token::Lt() => forj_parser::Token::Lt,
            Token::LtEq() => forj_parser::Token::LtEq,
            Token::Gt() => forj_parser::Token::Gt,
            Token::GtEq() => forj_parser::Token::GtEq,
            Token::GtGt() => forj_parser::Token::GtGt,
            Token::LtLt() => forj_parser::Token::LtLt,
            Token::GtGtEq() => forj_parser::Token::GtGtEq,
            Token::LtLtEq() => forj_parser::Token::LtLtEq,
            Token::GtGtGt() => forj_parser::Token::GtGtGt,
            Token::LtLtLt() => forj_parser::Token::LtLtLt,
            Token::GtGtGtEq() => forj_parser::Token::GtGtGtEq,
            Token::LtLtLtEq() => forj_parser::Token::LtLtLtEq,
            Token::MinusGt() => forj_parser::Token::MinusGt,
            Token::MinusGtGt() => forj_parser::Token::MinusGtGt,
            Token::LtMinusGt() => forj_parser::Token::LtMinusGt,
            Token::PlusPlus() => forj_parser::Token::PlusPlus,
            Token::MinusMinus() => forj_parser::Token::MinusMinus,
            Token::PlusColon() => forj_parser::Token::PlusColon,
            Token::MinusColon() => forj_parser::Token::MinusColon,
            Token::PlusSlashMinus() => forj_parser::Token::PlusSlashMinus,
            Token::PlusPercentMinus() => forj_parser::Token::PlusPercentMinus,
            Token::Paren() => forj_parser::Token::Paren,
            Token::EParen() => forj_parser::Token::EParen,
            Token::Bracket() => forj_parser::Token::Bracket,
            Token::EBracket() => forj_parser::Token::EBracket,
            Token::Brace() => forj_parser::Token::Brace,
            Token::EBrace() => forj_parser::Token::EBrace,
            Token::Colon() => forj_parser::Token::Colon,
            Token::SColon() => forj_parser::Token::SColon,
            Token::Apost() => forj_parser::Token::Apost,
            Token::Comma() => forj_parser::Token::Comma,
            Token::Period() => forj_parser::Token::Period,
            Token::Pound() => forj_parser::Token::Pound,
            Token::Dollar() => forj_parser::Token::Dollar,
            Token::At() => forj_parser::Token::At,
            Token::AtAt() => forj_parser::Token::AtAt,
            Token::Eq() => forj_parser::Token::Eq,
            Token::ColonColon() => forj_parser::Token::ColonColon,
            Token::ColonEq() => forj_parser::Token::ColonEq,
            Token::ColonSlash() => forj_parser::Token::ColonSlash,
            Token::PoundPound() => forj_parser::Token::PoundPound,
            Token::PoundMinusPound() => forj_parser::Token::PoundMinusPound,
            Token::PoundEqPound() => forj_parser::Token::PoundEqPound,
            Token::EqGt() => forj_parser::Token::EqGt,
            Token::StarGt() => forj_parser::Token::StarGt,
            Token::PipeMinusGt() => forj_parser::Token::PipeMinusGt,
            Token::PipeEqGt() => forj_parser::Token::PipeEqGt,
            Token::Bslash() => forj_parser::Token::Bslash,
            Token::PathpulseDollar() => forj_parser::Token::PathpulseDollar,
            Token::OneStep() => forj_parser::Token::OneStep,
            Token::DollarSetup() => forj_parser::Token::DollarSetup,
            Token::DollarHold() => forj_parser::Token::DollarHold,
            Token::DollarSetuphold() => forj_parser::Token::DollarSetuphold,
            Token::DollarRecovery() => forj_parser::Token::DollarRecovery,
            Token::DollarRemoval() => forj_parser::Token::DollarRemoval,
            Token::DollarRecrem() => forj_parser::Token::DollarRecrem,
            Token::DollarSkew() => forj_parser::Token::DollarSkew,
            Token::DollarTimeskew() => forj_parser::Token::DollarTimeskew,
            Token::DollarFullskew() => forj_parser::Token::DollarFullskew,
            Token::DollarPeriod() => forj_parser::Token::DollarPeriod,
            Token::DollarWidth() => forj_parser::Token::DollarWidth,
            Token::DollarNochange() => forj_parser::Token::DollarNochange,
            Token::DollarRoot() => forj_parser::Token::DollarRoot,
            Token::DollarUnit() => forj_parser::Token::DollarUnit,
            Token::DollarFatal() => forj_parser::Token::DollarFatal,
            Token::DollarError() => forj_parser::Token::DollarError,
            Token::DollarWarning() => forj_parser::Token::DollarWarning,
            Token::DollarInfo() => forj_parser::Token::DollarInfo,
            Token::OnelineComment { text } => {
                forj_parser::Token::OnelineComment(&text)
            }
            Token::BlockComment { text } => {
                forj_parser::Token::BlockComment(&text)
            }
            Token::UnsignedNumber { text } => {
                forj_parser::Token::UnsignedNumber(&text)
            }
            Token::FixedPointNumber { text } => {
                forj_parser::Token::FixedPointNumber(&text)
            }
            Token::BinaryNumber { text } => {
                forj_parser::Token::BinaryNumber(&text)
            }
            Token::OctalNumber { text } => {
                forj_parser::Token::OctalNumber(&text)
            }
            Token::DecimalNumber { text } => {
                forj_parser::Token::DecimalNumber(&text)
            }
            Token::HexNumber { text } => forj_parser::Token::HexNumber(&text),
            Token::ScientificNumber { text } => {
                forj_parser::Token::ScientificNumber(&text)
            }
            Token::UnbasedUnsizedLiteral { text } => {
                forj_parser::Token::UnbasedUnsizedLiteral(&text)
            }
            Token::SystemTfIdentifier { text } => {
                forj_parser::Token::SystemTfIdentifier(&text)
            }
            Token::SimpleIdentifier { text } => {
                forj_parser::Token::SimpleIdentifier(&text)
            }
            Token::EscapedIdentifier { text } => {
                forj_parser::Token::EscapedIdentifier(&text)
            }
            Token::PreprocessorIdentifier { text } => {
                forj_parser::Token::PreprocessorIdentifier(&text)
            }
            Token::TextMacro { text } => forj_parser::Token::TextMacro(&text),
            Token::ConcatenatedTextMacro { text } => {
                forj_parser::Token::ConcatenatedTextMacro(&text)
            }
            Token::StringLiteral { text } => {
                forj_parser::Token::StringLiteral(&text)
            }
            Token::PreprocessorStringLiteral { text } => {
                forj_parser::Token::PreprocessorStringLiteral(&text)
            }
            Token::TripleQuoteStringLiteral { text } => {
                forj_parser::Token::TripleQuoteStringLiteral(&text)
            }
            Token::PreprocessorTripleQuoteStringLiteral { text } => {
                forj_parser::Token::PreprocessorTripleQuoteStringLiteral(&text)
            }
            Token::Newline() => forj_parser::Token::Newline,
        }
    }
}

/// A source file [`Token`] with an associated [`Span`]
#[pyclass(eq, from_py_object, module = "forj_python", str)]
#[derive(Clone, PartialEq, Eq)]
pub struct SpannedToken {
    #[pyo3(get, set)]
    pub token: Token,
    #[pyo3(get, set)]
    pub span: Span,
}

impl<'a> From<forj_parser::SpannedToken<'a>> for SpannedToken {
    fn from(value: forj_parser::SpannedToken<'a>) -> Self {
        Self {
            token: value.0.into(),
            span: value.1.into(),
        }
    }
}

impl std::fmt::Display for SpannedToken {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.token.fmt(f)
    }
}

impl<'a> SpannedToken {
    /// Turn a [`SpannedToken`] into a [`forj_parser::SpannedToken`]
    pub fn to_rust(
        &'a self,
        cache: &'a PreprocessorCache<'a>,
    ) -> forj_parser::SpannedToken<'a> {
        forj_parser::SpannedToken(
            (&self.token).into(),
            (&self.span).to_span(cache),
        )
    }
}
